In [1]:
from rl4co.envs import FJSPEnv

In [2]:
from rl4co.envs import FJSPEnv
from rl4co.models.zoo.l2d import L2DModel
from rl4co.utils.trainer import RL4COTrainer
from pytorch_lightning.loggers import CSVLogger
# from pytorch_lightning.callbacks

import torch

import pandas as pd

import plotly.express as px

# Base model

In [3]:
generator_params = {
  "num_jobs": 20,  # the total number of jobs
  "num_machines": 10,  # the total number of machines that can process operations
  "min_ops_per_job": 1,  # minimum number of operatios per job
  "max_ops_per_job": 5,  # maximum number of operations per job
  "min_processing_time": 1,  # the minimum time required for a machine to process an operation
  "max_processing_time": 20,  # the maximum time required for a machine to process an operation
  "min_eligible_ma_per_op": 1,  # the minimum number of machines capable to process an operation
  "max_eligible_ma_per_op": 5,  # the maximum number of machines capable to process an operation
}

In [4]:
env = FJSPEnv(generator_params=generator_params)

In [5]:
if torch.cuda.is_available():
    accelerator = "gpu"
    batch_size = 256
    train_data_size = 5_000
    embed_dim = 256
    num_encoder_layers = 8
else:
    accelerator = "cpu"
    batch_size = 32
    train_data_size = 1_000
    embed_dim = 64
    num_encoder_layers = 2

accelerator

'gpu'

In [6]:
model = L2DModel(env,
                 baseline="rollout",
                 batch_size=batch_size,
                 train_data_size=train_data_size,
                 val_data_size=1_000,
                 optimizer_kwargs={"lr": 1e-5})

/home/daniil/programming/diplom/mtrlgnn/.venv/lib/python3.10/site-packages/lightning/pytorch/utilities/parsing.py:209: Attribute 'env' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['env'])`.
/home/daniil/programming/diplom/mtrlgnn/.venv/lib/python3.10/site-packages/lightning/pytorch/utilities/parsing.py:209: Attribute 'policy' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['policy'])`.

In [7]:
loggers = [
        CSVLogger(save_dir="logs", name="csv_logs"),
    ]

In [8]:
trainer = RL4COTrainer(
    max_epochs=20,
    accelerator=accelerator,
    devices=1,
    logger=loggers,
    log_every_n_steps=20
)

Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

In [11]:
trainer.fit(model)

val_file not set. Generating dataset instead
test_file not set. Generating dataset instead
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name     | Type           | Params | Mode
----------------------------------------------------
0 | env      | FJSPEnv        | 0      | train
1 | policy   | L2DPolicy      | 81.2 K | train
2 | baseline | WarmupBaseline | 81.2 K | train
----------------------------------------------------
162 K     Trainable params
0         Non-trainable params
162 K     Total params
0.649     Total estimated model params size (MB)
74        Modules in train mode
70        Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/daniil/programming/diplom/mtrlgnn/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/home/daniil/programming/diplom/mtrlgnn/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=20` reached.

In [8]:
model = L2DModel.load_from_checkpoint("./logs/csv_logs/version_0/checkpoints/epoch=19-step=400.ckpt")

/home/daniil/programming/diplom/mtrlgnn/.venv/lib/python3.10/site-packages/lightning/pytorch/core/saving.py:195: Found keys that are not in the model state dict but in the checkpoint: ['baseline.baseline.policy.encoder.init_embedding.init_ops_embed.weight', 'baseline.baseline.policy.encoder.init_embedding.pos_encoder.pe', 'baseline.baseline.policy.encoder.init_embedding.init_ma_embed.weight', 'baseline.baseline.policy.encoder.init_embedding.edge_embed.weight', 'baseline.baseline.policy.encoder.layers.0.hgnn1.self_attn', 'baseline.baseline.policy.encoder.layers.0.hgnn1.cross_attn', 'baseline.baseline.policy.encoder.layers.0.hgnn1.edge_attn', 'baseline.baseline.policy.encoder.layers.0.hgnn2.self_attn', 'baseline.baseline.policy.encoder.layers.0.hgnn2.cross_attn', 'baseline.baseline.policy.encoder.layers.0.hgnn2.edge_attn', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm1.normalizer.weight', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm1.normalizer.bias', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm1.normalizer.running_mean', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm1.normalizer.running_var', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm1.normalizer.num_batches_tracked', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.ffn.0.weight', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.ffn.0.bias', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.ffn.2.weight', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.ffn.2.bias', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm2.normalizer.weight', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm2.normalizer.bias', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm2.normalizer.running_mean', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm2.normalizer.running_var', 'baseline.baseline.policy.encoder.layers.0.ffn1.ops.norm2.normalizer.num_batches_tracked', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm1.normalizer.weight', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm1.normalizer.bias', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm1.normalizer.running_mean', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm1.normalizer.running_var', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm1.normalizer.num_batches_tracked', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.ffn.0.weight', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.ffn.0.bias', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.ffn.2.weight', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.ffn.2.bias', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm2.normalizer.weight', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm2.normalizer.bias', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm2.normalizer.running_mean', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm2.normalizer.running_var', 'baseline.baseline.policy.encoder.layers.0.ffn2.ops.norm2.normalizer.num_batches_tracked', 'baseline.baseline.policy.encoder.layers.1.hgnn1.self_attn', 'baseline.baseline.policy.encoder.layers.1.hgnn1.cross_attn', 'baseline.baseline.policy.encoder.layers.1.hgnn1.edge_attn', 'baseline.baseline.policy.encoder.layers.1.hgnn2.self_attn', 'baseline.baseline.policy.encoder.layers.1.hgnn2.cross_attn', 'baseline.baseline.policy.encoder.layers.1.hgnn2.edge_attn', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm1.normalizer.weight', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm1.normalizer.bias', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm1.normalizer.running_mean', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm1.normalizer.running_var', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm1.normalizer.num_batches_tracked', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.ffn.0.weight', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.ffn.0.bias', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.ffn.2.weight', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.ffn.2.bias', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm2.normalizer.weight', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm2.normalizer.bias', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm2.normalizer.running_mean', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm2.normalizer.running_var', 'baseline.baseline.policy.encoder.layers.1.ffn1.ops.norm2.normalizer.num_batches_tracked', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm1.normalizer.weight', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm1.normalizer.bias', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm1.normalizer.running_mean', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm1.normalizer.running_var', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm1.normalizer.num_batches_tracked', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.ffn.0.weight', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.ffn.0.bias', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.ffn.2.weight', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.ffn.2.bias', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm2.normalizer.weight', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm2.normalizer.bias', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm2.normalizer.running_mean', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm2.normalizer.running_var', 'baseline.baseline.policy.encoder.layers.1.ffn2.ops.norm2.normalizer.num_batches_tracked', 'baseline.baseline.policy.decoder.actor.dummy', 'baseline.baseline.policy.decoder.actor.mlp.lins.0.weight', 'baseline.baseline.policy.decoder.actor.mlp.lins.0.bias', 'baseline.baseline.policy.decoder.actor.mlp.lins.1.weight', 'baseline.baseline.policy.decoder.actor.mlp.lins.1.bias', 'baseline.baseline.policy.decoder.actor.mlp.lins.2.weight', 'baseline.baseline.policy.decoder.actor.mlp.lins.2.bias']
val_file not set. Generating dataset instead
test_file not set. Generating dataset instead

In [7]:
metrics = pd.read_csv("./logs/csv_logs/version_0/metrics.csv")

In [8]:
metrics

    epoch  step  train/loss  train/reward  val/reward
0       0    19 -125.342072    -92.742645         NaN
1       0    19         NaN           NaN  -94.300003
2       1    39  254.912247    -88.632355         NaN
3       1    39         NaN           NaN  -93.008003
4       2    59  155.156189    -91.911766         NaN
5       2    59         NaN           NaN  -90.515999
6       3    79   67.305183    -89.308823         NaN
7       3    79         NaN           NaN  -88.101997
8       4    99 -186.886505    -89.191177         NaN
9       4    99         NaN           NaN  -87.016998
10      5   119  -71.086624    -88.227943         NaN
11      5   119         NaN           NaN  -85.917000
12      6   139 -280.423401    -90.448532         NaN
13      6   139         NaN           NaN  -86.078003
14      7   159 -147.298019    -88.691177         NaN
15      7   159         NaN           NaN  -85.793999
16      8   179 -218.792053    -87.933823         NaN
17      8   179         NaN           NaN  -85.836998
18      9   199 -284.250000    -88.360298         NaN
19      9   199         NaN           NaN  -85.524002
20     10   219 -208.012070    -86.875000         NaN
21     10   219         NaN           NaN  -85.250000
22     11   239 -129.566666    -87.117645         NaN
23     11   239         NaN           NaN  -85.282997
24     12   259 -148.089447    -85.875000         NaN
25     12   259         NaN           NaN  -85.047997
26     13   279 -141.358231    -88.250000         NaN
27     13   279         NaN           NaN  -85.016998
28     14   299 -112.762268    -87.470589         NaN
29     14   299         NaN           NaN  -84.949997
30     15   319 -192.056641    -86.897057         NaN
31     15   319         NaN           NaN  -85.139000
32     16   339  -85.534904    -87.308823         NaN
33     16   339         NaN           NaN  -85.085999
34     17   359  -78.948158    -85.875000         NaN
35     17   359         NaN           NaN  -85.067001
36     18   379  -79.445686    -85.713234         NaN
37     18   379         NaN           NaN  -85.070999
38     19   399  -88.475365    -86.441177         NaN
39     19   399         NaN           NaN  -85.018997

In [9]:
metrics["val/reward"] = -metrics["val/reward"].shift(-1)
metrics["train/reward"] = -metrics["train/reward"]

In [10]:
metrics

    epoch  step  train/loss  train/reward  val/reward
0       0    19 -125.342072     92.742645   94.300003
1       0    19         NaN           NaN         NaN
2       1    39  254.912247     88.632355   93.008003
3       1    39         NaN           NaN         NaN
4       2    59  155.156189     91.911766   90.515999
5       2    59         NaN           NaN         NaN
6       3    79   67.305183     89.308823   88.101997
7       3    79         NaN           NaN         NaN
8       4    99 -186.886505     89.191177   87.016998
9       4    99         NaN           NaN         NaN
10      5   119  -71.086624     88.227943   85.917000
11      5   119         NaN           NaN         NaN
12      6   139 -280.423401     90.448532   86.078003
13      6   139         NaN           NaN         NaN
14      7   159 -147.298019     88.691177   85.793999
15      7   159         NaN           NaN         NaN
16      8   179 -218.792053     87.933823   85.836998
17      8   179         NaN           NaN         NaN
18      9   199 -284.250000     88.360298   85.524002
19      9   199         NaN           NaN         NaN
20     10   219 -208.012070     86.875000   85.250000
21     10   219         NaN           NaN         NaN
22     11   239 -129.566666     87.117645   85.282997
23     11   239         NaN           NaN         NaN
24     12   259 -148.089447     85.875000   85.047997
25     12   259         NaN           NaN         NaN
26     13   279 -141.358231     88.250000   85.016998
27     13   279         NaN           NaN         NaN
28     14   299 -112.762268     87.470589   84.949997
29     14   299         NaN           NaN         NaN
30     15   319 -192.056641     86.897057   85.139000
31     15   319         NaN           NaN         NaN
32     16   339  -85.534904     87.308823   85.085999
33     16   339         NaN           NaN         NaN
34     17   359  -78.948158     85.875000   85.067001
35     17   359         NaN           NaN         NaN
36     18   379  -79.445686     85.713234   85.070999
37     18   379         NaN           NaN         NaN
38     19   399  -88.475365     86.441177   85.018997
39     19   399         NaN           NaN         NaN

In [11]:
px.line(data_frame=metrics.dropna(), x="step", y=["train/reward", "val/reward"])

In [9]:
import torch
import gc

def clear_cuda_memory():
    gc.collect()  # Сборщик мусора Python
    torch.cuda.empty_cache()  # Очистка кэша CUDA
    # Дополнительно: сброс статистики памяти (необязательно)
    torch.cuda.reset_peak_memory_stats()

In [ ]:
def eval_model_on_env(model, env, test_size=1_000, batch_size=64):

    model.eval()

    torch.cuda.empty_cache()  # Чистим кэш CUDA

    res = []
    remind_n = test_size

    while remind_n > 0:
        print(remind_n, end="\r")

        bs = min(batch_size, remind_n)

        td = env.reset(batch_size=bs).to(model.device)

        out = model(td)

        res += out["reward"].cpu().tolist()  # Переносим на CPU перед конвертацией
        del td, out  # Удаляем ссылки
        torch.cuda.empty_cache()  # Чистим кэш CUDA

        remind_n = max(0, remind_n-batch_size)


    return -1* sum(res)/test_size

In [11]:
clear_cuda_memory()
eval_model_on_env(model, env, test_size=1_000, batch_size=64)

86.313

In [ ]:
class FJSPEnvAssamblyConstarints(FJSPEnv):
    def __init__(self, generator = None, generator_params = ..., mask_no_ops = True, check_mask = False, stepwise_reward = False, **kwargs):
        self.max_ops_processed = generator_params.pop("max_ops_processed")

        super().__init__(generator, generator_params, mask_no_ops, check_mask, stepwise_reward, **kwargs)

    def _reset(self, td = None, batch_size=None):
        td = super()._reset(td, batch_size)

        ma_ops_processed_left = torch.ones_like(td["busy_until"]) * self.max_ops_processed

        td["ma_ops_processed_left"] = ma_ops_processed_left

        return td.to(self.device)
    
    def _step(self, td):

        td = td.to(self.device)

        n_batches, n_jobs = td["end_op_per_job"].shape

        ma_ops_processed_left = td["ma_ops_processed_left"]

        n_machines = ma_ops_processed_left.size(1)

        machines = (td["action"] - 1) % n_machines

        ma_ops_processed_left[torch.arange(ma_ops_processed_left.size(0), device=self.device)[td["action"] > 0], machines[td["action"] > 0]] -= 1

        assert (ma_ops_processed_left >= 0).all()

        td = super()._step(td)

        td["ma_ops_processed_left"] = ma_ops_processed_left

        availible_machines_mask = (ma_ops_processed_left > 0)

        next_op_expanded = td["next_op"].unsqueeze(1).expand(-1, n_machines, -1)

        needed_machines = torch.gather(td["ops_ma_adj"], 2, next_op_expanded).sum(dim=-1)

        can_do_op = (availible_machines_mask * (needed_machines > 0)).any(dim=1, keepdim=True)

        new_mask = torch.concat([torch.tensor([True], device=self.device).bool().repeat(n_batches, 1), availible_machines_mask.repeat(1, n_jobs)], dim=1)

        new_mask = td["action_mask"] * new_mask

        all_false_rows = ~new_mask.any(dim=1)

        new_mask[all_false_rows, 0] = True

        td["action_mask"] = new_mask

        if (~can_do_op+td["done"]).any():

            td["time"][(~can_do_op+td["done"]).squeeze(1)] += 100*(~td["done"].squeeze(1)[(~can_do_op+td["done"]).squeeze(1)])

            td["done"][~can_do_op + td["done"]] = True

        return td

# New Env

In [12]:
new_generator_params = {**generator_params}
new_generator_params["max_ops_processed"] = 6

In [13]:
new_env = FJSPEnvAssamblyConstarints(generator_params=new_generator_params)

#### Reuse fited model with new env

In [23]:
clear_cuda_memory()
eval_model_on_env(model.to("cuda"), new_env, test_size=1_000, batch_size=64)

RuntimeError: output with shape [1] doesn't match the broadcast shape [1, 1]

In [ ]:
# def eval_model_w_function(env, next_action_func, batch_size=64, init_td=None):
#     td = env.reset(td=init_td, batch_size=batch_size)

#     while not td["done"].all():
#             action = next_action_func(td)
#             td["action"] = torch.Tensor([action]).to(int)

#             td = env.step(td)["next"]

#     td["reward"] = -td["time"]

#     return td

In [29]:
# import numpy as np

# def get_action_mwkr(td):

#         operation_mean_time = td["proc_times"][0].clone()
#         operation_mean_time[operation_mean_time == 0] = torch.nan
#         operation_mean_time = operation_mean_time.nanmean(dim=0)

#         n_machines = td["proc_times"].shape[1]

#         available_jobs, available_machines = torch.where(td["action_mask"][0, 1:].reshape(-1, n_machines))

#         if available_jobs.nelement() == 0:    
#             return 0

#         available_ops = td["next_op"][0, available_jobs]

#         last_ops = td["end_op_per_job"][0, available_jobs]

#         ops_remain = list(map(torch.arange, available_ops, last_ops+1))

#         work_remain = torch.Tensor(list(map(lambda x: operation_mean_time[x].sum(),  ops_remain)))

#         job_idx = available_jobs[np.argmax(work_remain)]

#         next_operation_index = td["next_op"][0][job_idx].item()

#         operation_proc_times = td["proc_times"][0][:, next_operation_index]

#         job_machine_mask = td["action_mask"][0][(1+job_idx*n_machines): (1+(job_idx+1)*n_machines)]

#         machine_idx = np.argmin(operation_proc_times + torch.inf*(1-job_machine_mask.to(int))).item()

#         action = 1 + job_idx*n_machines + machine_idx

#         return action

In [30]:
# init_td = env.reset(batch_size=1)
# init_td

In [ ]:
# e_td = eval_model_w_function(env=env, next_action_func=get_action_mwkr, batch_size=None, init_td=init_td.clone())
# e_td["reward"]

tensor([-70.])

In [ ]:
# e_td = eval_model_w_function(env=new_env, next_action_func=get_action_mwkr, batch_size=None, init_td=init_td)
# e_td["reward"]

tensor([-74.])

#### Finetune base model

In [14]:
model = model.to("cuda")

In [15]:
model.env = new_env.to("cuda")

In [16]:
trainer = RL4COTrainer(
    max_epochs=7,
    accelerator=accelerator,
    devices=1,
    logger=loggers,
    log_every_n_steps=20
)

Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

In [17]:
trainer.fit(model)

val_file not set. Generating dataset instead
test_file not set. Generating dataset instead
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name     | Type                       | Params | Mode
----------------------------------------------------------------
0 | env      | FJSPEnvAssamblyConstarints | 0      | train
1 | policy   | L2DPolicy                  | 81.2 K | train
2 | baseline | WarmupBaseline             | 81.2 K | train
----------------------------------------------------------------
162 K     Trainable params
0         Non-trainable params
162 K     Total params
0.649     Total estimated model params size (MB)
74        Modules in train mode
70        Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/daniil/programming/diplom/mtrlgnn/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
/home/daniil/programming/diplom/mtrlgnn/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=7` reached.

In [47]:
metrics = pd.read_csv("./logs/csv_logs/version_1/metrics.csv")
metrics["val/reward"] = -metrics["val/reward"].shift(-1)
metrics["train/reward"] = -metrics["train/reward"]

In [48]:
metrics

    epoch  step  train/loss  train/reward  val/reward
0       0    19 -151.430713     90.510518   89.281318
1       0    19         NaN           NaN         NaN
2       1    39  -40.538391     87.598164   88.390195
3       1    39         NaN           NaN         NaN
4       2    59 -234.075898     92.701182   87.597744
5       2    59         NaN           NaN         NaN
6       3    79  -55.274390     87.597578   87.389756
7       3    79         NaN           NaN         NaN
8       4    99  -67.898560     87.591182   87.787598
9       4    99         NaN           NaN         NaN
10      5   119  170.914375     86.141982   87.986104
11      5   119         NaN           NaN         NaN
12      6   139  -18.431360     84.675146   87.986104
13      6   139         NaN           NaN         NaN

In [50]:
px.line(data_frame=metrics.dropna(), x="step", y=["train/reward", "val/reward"])

#### Refit base model

In [74]:
metrics = pd.read_csv("./logs/csv_logs/metrics_refit.csv")
metrics["val/reward"] = -metrics["val/reward"].shift(-1)
metrics["train/reward"] = -metrics["train/reward"]

In [75]:
px.line(data_frame=metrics.dropna(), x="step", y=["train/reward", "val/reward"])

#### Fit full new model

In [81]:
metrics = pd.read_csv("./logs/csv_logs/metrics_fit_new.csv")
metrics["val/reward"] = -metrics["val/reward"].shift(-1)
metrics["train/reward"] = -metrics["train/reward"]

In [82]:
px.line(data_frame=metrics.dropna(), x="step", y=["train/reward", "val/reward"])

#### Fit only additional encoder

In [87]:
metrics = pd.read_csv("./logs/csv_logs/metrics_finetune.csv")
metrics["val/reward"] = -metrics["val/reward"].shift(-1)
metrics["train/reward"] = -metrics["train/reward"]

In [88]:
px.line(data_frame=metrics.dropna(), x="step", y=["train/reward", "val/reward"])

In [106]:
metrics1 = pd.read_csv("./logs/csv_logs/version_1/metrics.csv")
metrics2 = pd.read_csv("./logs/csv_logs/metrics_refit.csv")
metrics3 = pd.read_csv("./logs/csv_logs/metrics_fit_new.csv")
metrics4 = pd.read_csv("./logs/csv_logs/metrics_finetune.csv")

In [107]:
metrics1["name"] = "Finetune base"
metrics2["name"] = "Refit base"
metrics3["name"] = "Fit new"
metrics4["name"] = "Base Lora"

In [108]:
m = pd.concat([metrics1, metrics2, metrics3, metrics4])

In [109]:
m["val/reward"] *= -1

In [110]:
px.line(data_frame=m.dropna(subset=["val/reward"]), x="step", y="val/reward", color="name")